using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyCopyrightAttribute("Released by Jeremy D. Miller under the Apache 2.0 License")]
[assembly: AssemblyProductAttribute("FluentNHibernate")]
[assembly: AssemblyCompanyAttribute("FluentNHibernate")]
[assembly: AssemblyConfigurationAttribute("debug")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.0")]

